services:
  app-unahur-portal:
    profiles:
      - app
    build: .
    image: unahur/app-portal:1.0
    container_name: app-unahur-portal
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DB_HOST: app-unahur-portal-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
    volumes:
      - ./:/app 
      - /app/node_modules 
    networks:
      - ms-unahur-portal-network
    depends_on:
      - app-unahur-portal-db

  app-unahur-portal-db:
    image: postgres:15
    container_name: app-unahur-portal-db
    ports:
      - "${DB_PORT_EXTERNAL:-5433}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-app-unahur-portal}
    networks:
      - ms-unahur-portal-network

  app-unahur-pgadmin:
    profiles:
      - tools
    image: dpage/pgadmin4
    container_name: app-unahur-pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminpassword}
    networks:
      - ms-unahur-portal-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    networks:
      - ms-unahur-portal-network


networks:
  ms-unahur-portal-network:
    driver: bridge
