services:
  app-unahur-portal:
    build: .
    image: unahur/app-portal:1.0
    container_name: app-unahur-portal
    ports:
      - "9002:9002" # Modificar luego por ${PORT}:${PORT}
    environment:
      - PORT=9002 # Modificar luego por ${PORT}
      - DB_HOST=app-unahur-portal-db # Modificar luego por ${DB_HOST}
      - DB_PORT=5432 # Modificar luego por ${DB_PORT}
    volumes:
      - ./:/app 
      - /app/node_modules 
    networks:
      - ms-unahur-portal-network
  app-unahur-portal-db:
    image: postgres:15
    container_name: app-unahur-portal-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - ms-unahur-portal-network

networks:
  ms-unahur-portal-network:
    driver: bridge